create or replace PACKAGE PK_TE_EX AS 

EX_TE_GENERAL exception;
CEX_TE_GENERAL constant pls_integer := -20999;
pragma EXCEPTION_INIT( EX_TE_GENERAL, -20999 );

EX_TE_OF_WRONG_TYPE exception;
CEX_TE_OF_WRONG_TYPE constant pls_integer := -20998;
pragma EXCEPTION_INIT( EX_TE_OF_WRONG_TYPE, -20998 );

EX_TE_IS_NULL exception;
CEX_TE_IS_NULL constant pls_integer := -20997;
pragma EXCEPTION_INIT( EX_TE_IS_NULL, -20997 );

EX_CURSOR_OF_WRONG_TYPE exception;
CEX_CURSOR_OF_WRONG_TYPE constant pls_integer := -20996;
pragma EXCEPTION_INIT( EX_CURSOR_OF_WRONG_TYPE, -20996 );

EX_WRONG_PH_DENOTATION exception;
CEX_WRONG_PH_DENOTATION constant pls_integer := -20995;
pragma EXCEPTION_INIT( EX_WRONG_PH_DENOTATION, -20995 );

EX_TY_TE_TYPES_DO_NOT_MATCH exception;
CEX_TY_TE_TYPES_DO_NOT_MATCH constant pls_integer := -20994;
pragma EXCEPTION_INIT( EX_TY_TE_TYPES_DO_NOT_MATCH, -20994 );

EX_EVAL_FAILED exception;
CEX_EVAL_FAILED constant pls_integer := -20993;
pragma EXCEPTION_INIT( EX_EVAL_FAILED, -20993 );

END PK_TE_EX;
/